### ISSUE TITLE
Missing pandas API functions

### ISSUE THREAD

**Issue by nipsn** [hablapps/pykx#4]
**Is your feature request related to a problem? Please describe.**
It would be useful for users to be able to use their existing and tested pandas code, and at the moment there are functions missing implementation on the pandas API.

**Describe the solution you'd like**
An implementation of the pandas functions provided below that followed their original interface.

**Describe alternatives you've considered**

**Additional resources**
These are the functions without implementation that we could find. If more were to be found, they would be added to this list.

| Function| Branch/PR | Done| Status |
|--------|--------|--------|--------|
| `melt` | [pandas_melt](https://github.com/hablapps/pykx/tree/marcosvm13/pandas_api_melt) | <ul><li> - [ ]  </li></ul> | In progress (Marcos) |
| `concat` | - | <ul><li> - [ ]  </li></ul> | - |
| `get_dummies` | [pandas_api_get_dummies](https://github.com/hablapps/pykx/tree/marcosvm13/pandas_api_get_dummies) | <ul><li> - [ ]  </li></ul> | In progress (Marcos Deprecated) |
| `from_dummies` | - | <ul><li> - [ ]  </li></ul> | - |
| `unique` | - | <ul><li> - [ ]  </li></ul> | - | 
| `isna` | - | <ul><li> - [ ]  </li></ul> | - |
| `isnull` | - | <ul><li> - [ ]  </li></ul> | - |
| `to_numeric` | - | <ul><li> - [ ]  </li></ul> | - | 
| `to_datetime` | [pandas_api_to_datetime](https://github.com/hablapps/pykx/tree/marcosvm13/pandas_api_to_datetime) | <ul><li> - [ ]  </li></ul> | In progress (Marcos Deprecated)|
| `to_timedelta` | - | <ul><li> - [ ]  </li></ul> | - |
| `values` | - | <ul><li> - [ ]  </li></ul> | In progress (Tian) | 
| `empty` | - | <ul><li> - [ ]  </li></ul> | - |
| `keys` | - | <ul><li> - [ ]  </li></ul> | - |
| `isin` | - | <ul><li> - [ ]  </li></ul> | - | 
| `mask` | - | <ul><li> - [ ]  </li></ul> | - |
| Addition | - | <ul><li> - [ ]  </li></ul> | - |
| Substraction | - | <ul><li> - [ ]  </li></ul> | - | 
| Element-wise multiplication | - | <ul><li> - [ ]  </li></ul> | - |
| Dot multiplication | - | <ul><li> - [ ]  </li></ul> | - |
| Less than | - | <ul><li> - [ ]  </li></ul> | - | 
| Greater than | - | <ul><li> - [ ]  </li></ul> | - |
| Equal | - | <ul><li> - [ ]  </li></ul> | - |
| `map` | - | <ul><li> - [ ]  </li></ul> | - | 
| `rolling` | - | <ul><li> - [ ]  </li></ul> | - |
| `clip` | - | <ul><li> - [ ]  </li></ul> | - |
| `round` | /pull/7 | <ul><li> - [ ]  </li></ul> |In progress (Oscar) | 
| `corr` | - | <ul><li> - [ ]  </li></ul> | - | 
| `kurt` | /pull/6 | <ul><li> - [ ]  </li></ul> | In progress (Miguel)| 
| `count` | /pull/2 | <ul><li> - [ ]  </li></ul> | 1st PR | 
| `quantile` | - | <ul><li> - [ ]  </li></ul> | - | 
| `rank` | - | <ul><li> - [ ]  </li></ul> | - | 
| `sem` | - | <ul><li> - [ ]  </li></ul> | - | 
| `std` | /pull/3 | <ul><li> - [ ]  </li></ul> | 1st PR | 
| `skew` | /pull/1 | <ul><li> - [ ]  </li></ul> | 1st PR| 
| `nunique` | /pull/9 | <ul><li> - [ ]  </li></ul> | Ready for review | 
| `add_prefix` | /pull/8 | <ul><li> - [ ]  </li></ul> | 1st PR| 
| `add_suffix` | /pull/8 | <ul><li> - [ ]  </li></ul> |1st PR| 
| `at_time` | - | <ul><li> - [ ]  </li></ul> | - | 
| `between_time`| - | <ul><li> - [ ]  </li></ul> | - | 
| `id_max` | - | <ul><li> - [ ]  </li></ul> | - | 
| `id_min` | - | <ul><li> - [ ]  </li></ul> | - | 
| `sample` | - | <ul><li> - [ ]  </li></ul> | - |

**Comment by neutropolis** [comment]
I've moved this table to a discussion page: https://github.com/hablapps/pykx/discussions/19
